version: '3'
services:
  airflowproject:
    build:
        context: .
        dockerfile: Dockerfile.airflow
    env_file:
      - .env
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"
    command: airflow standalone

  metaduck:
    build:
      context: .
      dockerfile: Dockerfile.metaduck
    container_name: metaduck
    ports:
      - "3000:3000"
    environment:
      - MB_PLUGINS_DIR=/home/plugins
    volumes:
      - ./data:/data
