version: '3'
services:
  airflowproject:
    build:
        context: .
        dockerfile: Dockerfile.airflow
    env_file:
      - .env
    volumes:
      - ./airflow:/opt/airflow
      - ./data:/data
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"
    command: airflow standalone

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    volumes:
      - ./dbt:/dbt
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
      - ./data:/data
    working_dir: /dbt
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh", "-c", "while [ ! -f /data/youtube_data.csv ]; do echo 'Esperando CSV...'; sleep 2; done; dbt run"]


  metaduck:
    build:
      context: .
      dockerfile: Dockerfile.metaduck
    container_name: metaduck
    ports:
      - "3000:3000"
    environment:
      - MB_PLUGINS_DIR=/home/plugins
    volumes:
      - ./data:/data
volumes: {}