FROM openjdk:19-buster

ENV MB_PLUGINS_DIR=/home/plugins

# Crear carpeta plugins
RUN mkdir -p /home/plugins

# Descargar Metabase
ADD https://downloads.metabase.com/v0.52.4/metabase.jar /home

# Descargar el driver DuckDB
ADD https://github.com/MotherDuck-Open-Source/metabase_duckdb_driver/releases/download/0.2.12/duckdb.metabase-driver.jar /home/plugins

RUN chmod 744 /home/plugins/duckdb.metabase-driver.jar

CMD ["java", "-jar", "/home/metabase.jar"]
